apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prom-stack
  namespace: monitoring-system
spec:
  interval: 1m0s
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '62.6.0'
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: flux-system