apiVersion: v1
data:
    DB_HOST: MTkyLjE2OC4xLjIz
    DB_NAME: ZmliZXItYXBw
    DB_USER: cG9zdGdyZXM=
    DB_PASSWORD: cG9zdGdyZXM=
    DB_PORT: NTQzMg==
kind: Secret
metadata:
    name: notes-api-demo-secret
type: Opaque
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notes-api-demo
  name: notes-api-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes-api-demo
  template:
    metadata:
      labels:
        app: notes-api-demo
    spec:
      containers:
      - image: 10969ra/notes-api-demo:dev-latest
        name: notes-api-demo
        ports:
        - containerPort: 3000
        envFrom:
          - secretRef:
              name: notes-api-demo-secret
---
apiVersion: v1
kind: Service
metadata:
  name: notes-api-demo-svc
spec:
  type: NodePort 
  selector:
    app: notes-api-demo
  ports:
  - name: notes-api-demo
    port: 3000
    targetPort: 3000

