apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 2
  template:
    spec:
      containers:
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: notes-api-demo-dev-secret
