apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: notes-api-demo-dev-ns
namePrefix: notes-api-demo-dev
labels:
  - pairs:
      app: notes-api-demo
    includeSelectors: true 
    includeTemplates: true 
resources:
- ../../base

patches:
- path: deployment.yml
- path: service.yml